# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Krittika- The Astronomy Club of IITB
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Krittika. All Rights Reserved.'
credits: 'Credits: <ul> <li> <a href = https://www.facebook.com/chinmay0301> Chinmay Talegaonkar</a> </li> <li> <a href = https://www.facebook.com/profile.php?id=100010041307477> Tanya Choudhary</a> </li> </ul> '

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

  - title: github
    url: https://github.com/T4ti4na/krittika
  - title: facebook
    url: https://www.facebook.com/groups/krittika.iitb/
